install.packages("tidyverse")
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(readr)
library(purrr)
library(stringr)
library(forcats)

snake <- read.csv("BlackButler.csv")
levi <- read.csv("ObeyMe.csv")
demons <- bind_rows(snake, levi)
str(demons)
demons
write.csv(demons, file = "Demons.csv")
